### ISSUE TITLE
Named export "filedirname"

### ISSUE THREAD

**Issue by PabloSzx** [bevry/filedirname#148]
Hi @balupton, and thank you for this useful library, I recently mentioned it in a recent blog post where I talk about ESM https://the-guild.dev/blog/support-nodejs-esm, it's very useful since it gives you an isomorphic solution for __dirname and __filename, which is really useful for being able to support CommonJS & ESM with a single source file, but I feel like where is a missing piece which is that this package doesn't do a named export of filedirname, which in practice means that when trying to do an isomorphic import, you need to rely on features like https://www.typescriptlang.org/tsconfig#esModuleInterop to be able to use the "default" export in both environments, which I don't think is the best solution.

For that reason (and many others, like helping auto-import logic), "filedirname" should also be exported with name, that is:

```ts
export function filedirname(arg?: Error | string): Result {
	// nothing
	if (arg == null) {
		return filedirnameFromCaller()
	}

	// string
	if (typeof arg === 'string') {
		return filedirnameFromPath(arg)
	}

	// error
	return filedirnameFromError(arg)
}
export default filedirname
```

Which means that you can safely do:

```ts
const { filedirname } = require("filedirname");

# or

import { filedirname } from "filedirname";
```

without needing an extra helper function in the transpilation process to be able to use the "default".

I hope this explanation helps 😄

**Comment by balupton** [comment]
Seems fine to me, I'll merge it in later. Reading your post, you might be interested in our https://github.com/bevry/boundation project which automates everything but the source code away, such as generating the esm, cjs, deno, and browser editions and editions for specific ecmascript version targets, with tested compatibility. I can give you a demo of it if you want https://balupton.com/meet - myself and sindre maintain about the same amount of packages, but I use automated tooling to support everything whereas he hasn't figured that out.
